apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense-tracker
  labels:
    app.kubernetes.io/part-of: expense-tracker
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense-tracker
  labels:
    app.kubernetes.io/part-of: expense-tracker
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: expense-tracker
        app.kubernetes.io/name: frontend
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: expense-tracker/frontend:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
